version: '3.8'

services:
  django:
    build:
      context: .
    container_name: thecode
    ports:
      - "8002:8000"
    environment:
      - DEBUG=False
    working_dir: /app/thecode
    command: gunicorn thecode.wsgi:application --bind 0.0.0.0:8000
